FROM nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04

# fix (tzdata)
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get install -y python3-pip python3-dev

RUN apt-get install -y locales git vim

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
# some info to avoid interactivity in a package R requires
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# install system packages
RUN apt-get update --fix-missing && apt-get upgrade -y && apt-get install -y \
    apt-transport-https \
    software-properties-common \
    build-essential \
    libcurl4-gnutls-dev \
    libxml2-dev \
    libssl-dev \
    cmake \
    libfontconfig1-dev \
    libharfbuzz-dev \
    libfribidi-dev \
    libfreetype6-dev \
    libpng-dev \
    libtiff5-dev \
    libjpeg-dev \
    git \
    r-base r-base-core r-recommended r-base-dev

# install R packages
RUN R -e "install.packages('devtools')"
RUN R -e "devtools::install_version('tidyverse', version = '1.3.1', dependencies= T)"
RUN R -e "devtools::install_version('lme4', version = '1.1-29', dependencies= T)"
RUN R -e "devtools::install_version('broom.mixed', version = '0.2.9.4', dependencies= NA)"


# install python packages
RUN pip3 install git+https://github.com/candemircan/NaturalCogSci.git


RUN pip3 install tensorflow==2.9.1 tensorflow-hub==0.13.0

RUN pip3 install torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113

RUN pip3 install fasttext==0.9.2 \
    jupyterlab==3.6.1 \
    openai==0.27.2 \
    seaborn==0.12.2 \
    thingsvision==2.4.1 \
    transformers==4.26.1 \
    git+https://github.com/openai/CLIP.git \
    git+https://github.com/serre-lab/Harmonization.git 

# define environment variables
RUN echo "EXPORT NATURALCOGSCI_ROOT=/home/NaturalCogSci" >> ~/.bashrc
RUN echo "NATURALCOGSCI_ROOT=/home/NaturalCogSci" >> ~/.Renvironment

WORKDIR /home
